import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/components/ReactQuery/QueryProvider";
import { AuthProvider } from "@/components/AuthContext";
import { SocketContextProvier } from "@/provider/SocketContextProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <AuthProvider>
          <QueryProvider>
            <SocketContextProvier>{children}</SocketContextProvier>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
